let word1 = 'hello';
console.log(word1);
let word2 = 'owu';
console.log(word2);
let word3 = 'com';
console.log(word3);
let word4 = 'ua';
console.log(word4);
let number1 = '1';
console.log(number1);
let number2 = '10';
console.log(number2);
let number3 = '-999';
console.log(number3);
let number4 = '123';
console.log(number4);
let number5 = '3.14';
console.log(number5);
let number6 = '2.7';
console.log(number6);
let number7 = '16';
console.log(number7);
let word5 = 'true';
console.log(word5);
let word6 = 'false';
console.log(word6);